### PR TITLE
Allow passing env var for config json

### PR DESCRIPTION
**Pull request by MohammedAl-Rowad**
Small change to allow us to pass the path for a `.json` config file, if not passed it will fallback to `default.json` 

now to run any make command that uses `docker-compose.yml` you can do it like this to pass the path for the `.json` configs

```bash
PROGS_CFG='/app/b2b.json' make dev.nfs.up 
```

### CODE REVIEW

**Comment by MohammedAl-Rowad** [comment]
**Something important to remember: the environment variables inside the container won't be available if you run a command from outside the container and that might happen in 2 cases**

- if you don't use the commands from the makefile 
- if you run npm scripts from outside the container or without the make commands 

so we should always use the make commands.
I used to run npm scripts from outside the container, for now, it's fine but if we moved to Wepback and it has to read the  `PROGS_CFG` variable we need to use make commands

**Comment by MohammedAl-Rowad** [comment]
```bash
PROGS_CFG='/app/docker.json' make edraak.programs.compile_static
```

for example, to run `compilestatic` you need this now

**Comment by MohammedAl-Rowad** [comment]
Might be a little bit annoying to keep adding the path for the configs but it's nice that we can change it in an easy way

**Comment by MohammedAl-Rowad** [comment]
@devalih What do you think of this change? can I have your input on this

**Comment by devalih** [comment]
Hey man
I think this is better archived by adding docker.json to gitignore in progs repo, and copy the current content of docker.json to default.json, add one more step to provision script to copy default to docker.json.

This way you can change your settings as you want without getting git involved.

**Comment by Salomari1987** [comment]
@devalih the thing is we have very different two environments; b2b standalone platform and Edraak setup. So the idea here is to have configuration files saved for each environment, and you would pass the configuration file you need when provisioning or even running the devstack.

It is much better to keep this in git because now we can operate the devstack box like we do deployments. Imagine when doing deployments every devops or dev must create an ignored file and figure out what to place inside it from variables and settings, that would be aweful wouldn't it?

I dont see why this is a bad idea. Why do you think your suggestion is better @devalih ?

**Comment by shadinaif** [comment]
@Salomari1987 you might want to create a `.env` file containing the default value for `PROGS_CFG` to avoid the mandatory envirenment variable value in the command https://docs.docker.com/compose/environment-variables/#the-env-file

**Comment by umar221b** [comment]
Closing stale PR.

**Pull request closed without merging**
